### ISSUE TITLE
Empty clauses are ignored

### ISSUE THREAD

**Issue by sacado** [wkschwartz/pigosat#14]
When calling `Pigosat.AddClauses`, empty clauses are ignored.

This is an issue as the user calling `p.AddClauses(Clause{})` would expect the formula to be UNSAT and this behavior is not documented.

**Comment by wkschwartz** [comment]
I can be convinced otherwise, but I'm not entirely convinced empty clauses ought to evaluate to false in a CNF. I can see it being more intuitive for an empty clause implicitly always to be satisfied. Are there other SAT solvers that use that convention? How does the mathematical literature on SAT treat empty clauses -- can you link any citations?

Either way, I agree the documentation should be updated.

**Comment by sacado** [comment]
Well the literature seems to actually define an UNSAT formula as one from which one can derive the empty clause. For instance, the "handbook of satisfiability" states, (section 3.2, page 100) : "One important fact that we will base our future discussions on is that if a CNF formula implies the empty clause, the formula is essentially unsatisfiable."

> Are there other SAT solvers that use that convention?

As far as I know, all solvers behave the same way : for instance, the following DIMACS formula

    p cnf 2 2
    1 2 0
    0

is supposed to be declared UNSAT since it contains an empty clause. I just checked with minisat, glucose and picosat itself (hence the reason I think this is undesirable behavior).

Actually, this is the way most SAT solvers prove a formula is UNSAT : by deducing the empty clause through clause learning. For instance, from the formula

    (a or b) and (-a or b)

we can deduce the new clause

    (b)

And from the formula

    (a or b) and (-a or b) and (a or -b) and (-a or -b)

we can deduce two new clauses 

    (a) and (-a)

from which we can infer a new, empty clause :

    ()

Since no literal in this clause can be made true no matter what, the formula is thus declared UNSAT.

Directly providing a solver with an empty clause seems rather useless, but more often than not CNF formulas are generated / simplified by preprocessors rather than manually created. This is the "bug" I ran into with pigosat. I fed my preprocessor with a formula that happened to be UNSAT. The preprocessor simplified the formula, replacing a few clauses by an empty clause, i.e. by feeding pigosat with a clause containing `Clause{}`. I discovered the problem as the preprocessor I wrote, when generating DIMACS .cnf files that were fed to external sat solvers, instead of directly "feeding" pigosat, did not produce the same results.

**Comment by wkschwartz** [comment]
Very informative, thanks. All of that makes sense to me.

Do you have a patch you can send as a pull request?

**Comment by wkschwartz** [comment]
If you have a patch, I'd still really appreciate it, but if not, a test case would be helpful. Patching `AddClauses` will be very easy, but a test case from you would help me make sure I'm interpreting your ticket correctly.

**Comment by sacado** [comment]
I think I'll be able to submit a patch. I've identified the line to be
changed. I'll submit it ASAP.

Thanks.

2015-07-02 20:42 GMT+02:00 William Schwartz <notifications@github.com>:

> If you have a patch, I'd still really appreciate it, but if not, a test
> case would be helpful. Patching AddClauses will be very easy, but a test
> case from you would help me make sure I'm interpreting your ticket
> correctly.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/wkschwartz/pigosat/issues/14#issuecomment-118121500>.
>



-- 
    |\___
(:> ___ |3  Fabien Delorme
   |/
